### ISSUE TITLE
Todo App Todo 필터링 기능 추가하기

### ISSUE THREAD

**Issue by jeein2222** [jeein2222/Todo-App#3]
### 만들고자 하는 기능이 무엇인가요?
Todo 정렬, 필터링

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Todo 검색 기능
2. [ ] Todo 정렬 기능
3. [ ] Todo 필터링 기능
